### ISSUE TITLE
Spark master and worker passwd Error

### ISSUE THREAD

**Issue by sixpac009** [redhatanalytics/openshift-spark#4]
Tried out your repo on my cdk by using the 'make create' which works in setting it up in openshift  with a Spark Master and Spark workers but when I check the logs it fails with error below.   Am I missing something in the configuration that is needed to set the passwd?

    NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
    NWRAP_ERROR(15) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(15) - nwrap_files_getpwuid: Error loading passwd file
    NWRAP_ERROR(15) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(15) - nwrap_files_getpwuid: Error loading passwd file
    NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
    NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
    Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
    16/07/29 19:35:03 INFO Master: Started daemon with process name: 1@spark-master-oi55-1-d31jp
    16/07/29 19:35:03 INFO SignalUtils: Registered signal handler for TERM
    16/07/29 19:35:03 INFO SignalUtils: Registered signal handler for HUP
    16/07/29 19:35:03 INFO SignalUtils: Registered signal handler for INT
    16/07/29 19:35:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
    NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/passwd' readonly -1:No such file or directory
    NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
    Exception in thread "main" java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:823)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:760)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:633)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2181)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2181)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2181)
        at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:217)
        at org.apache.spark.deploy.master.Master$.startRpcEnvAndEndpoint(Master.scala:1024)
        at org.apache.spark.deploy.master.Master$.main(Master.scala:1009)
        at org.apache.spark.deploy.master.Master.main(Master.scala)
    Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
        at com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)
        at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:798)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:760)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:633)

        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2181)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2181)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2181)
        at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:217)
        at org.apache.spark.deploy.master.Master$.startRpcEnvAndEndpoint(Master.scala:1024)
        at org.apache.spark.deploy.master.Master$.main(Master.scala:1009)
        at org.apache.spark.deploy.master.Master.main(Master.scala)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:798)

**Comment by crobby** [comment]
I think you just need to set SPARK_USER=<anything> before running.

**Comment by crobby** [comment]
See also common.sh, which is included in the pod

**Comment by sixpac009** [comment]
It seems from the error it isn't running the common.sh b/c it can't find the /tmp/passwd file.
I am not seeing any where in the code that would read the SPARK_USER= parameter.

**Comment by tmckayus** [comment]
Very strange. I just cloned the repo and modified the Makefile to push to my integrated respoitory, did a make create and successfully launched. All workers registered with the master, and I have a /tmp/passwd file in the worker pods.

**Comment by tmckayus** [comment]
For what it's worth, when I've run spark-submit from a pod pointed at the spark master, I have to run common.sh in my shell first, the spark-submit.  Hope that helps.

**Comment by mattf** [comment]
@sixpac009 there's probably an environmental difference at play here. will you describe what you mean by "on my cdk"?

**Comment by sixpac009** [comment]
The cdk is redhats Container Development Kit that runs on any desktop
system.  Its a vagrant setup that launches a virtualbox VM with Openshift.

**Comment by mattf** [comment]
unfortunately i don't have the cdk up on my machine to reproduce -- "oc cluster up" is all that's needed on fedora.

see if you can connect to the master pod (oc rsh spark-master-...) and check id as well as perms on /tmp and if you can run /common.sh

**Comment by sixpac009** [comment]
I figured out what is happening. When the start-master or start-worker call common.sh they are never getting inside the IF statement ! $(getent passwd $(id -u)) .  I was able to run the container with a bash connection and modified the common.sh to run the code inside the IF and the container started up without errors.  From what I can tell the common.sh is expecting to be run by a user that wouldn't be in passwd file but how would that even be possible?

**Comment by mattf** [comment]
openshift's default configuration runs containers as an ephemeral
uid[0], e.g. 1000030000, for security purposes. those ids are
essentially never in /etc/passwd, which causes problems for core
hadoop libraries.

openshift can be configured to run containers as root or a know user,
through changing security context constraints and use of runasuser.

are you making scc/runasuser changes or does the cdk do that
automatically for you? if the latter we should talk to the cdk folks
to provide better integration. i recommend against the former, because
a production deployment of openshift likely will not let you continue
to manage the uid.

[0] https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html
search for "Support Arbitrary User IDs"
